version: '2'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - MySQL.env
    volumes:
      - ./datadir:/var/lib/mysql
  web:
    build: .
    env_file:
      - MySQL.env
      - Shinobi.env
    volumes:
      - ./docker-entrypoint.sh:/opt/shinobi/docker-entrypoint.sh
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/config
      - ./videos:/opt/shinobi/videos
    depends_on:
      - db
    ports:
      - "8080:80"
